name: keralum
analytics:
  google: ca-pub-2012905995297484
github: true
description: fast and simple media
author:
  name: Shaine Mata
  url: 'http://www.keralum.com'
  email: shaine@keralum.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F272481700%3Fapp_id%3D122963&dntp=1&url=https%3A%2F%2Fvimeo.com%2F272481700&image=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F704045503_1280.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=vimeo"
      width="1000" height="563" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Shaine Mata
          url: 'https://vimeo.com/user2412947'
          avatar: {}
      related: []
      publisher:
        url: 'https://vimeo.com/'
        name: Vimeo
        favicon: 'https://f.vimeocdn.com/images_v6/favicon.ico'
        domain: vimeo.com
      keywords: []
      description: >-
        This is "Untitled" by Shaine Mata on Vimeo, the home for high quality
        videos and the people who love them.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vimeo://app.vimeo.com/videos/272481700'
          type: ios
          namespace: ai
          app_name: Vimeo
          app_store_id: '425194759'
        - should_fallback: 'true'
          app_name: Vimeo
          package: com.vimeo.android.videoapp
          url: 'vimeo://app.vimeo.com/videos/272481700'
          namespace: ai
          type: web
        - url: 'vimeo://app.vimeo.com/videos/272481700'
          namespace: twitter
          type: ipad
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/272481700'
          namespace: twitter
          type: iphone
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/272481700'
          namespace: twitter
          type: googleplay
          name: Vimeo
          id: com.vimeo.android.videoapp
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://vimeo.com/272481700'
      title: Untitled
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: About
    id: 8a0cf19c-6e3a-4055-b9f4-a76e58956d27
    type: content
  - name: Home
    id: 52537b89-815f-4e3f-8103-738db69d8eaf
    type: content
  - name: Contact
    id: 282b4288-344f-4345-a791-4b015808843f
    type: content
  - name: Works
    id: 427e5ba1-2c22-4f2b-8b6b-c8e5a5e9a36b
    type: content
layout_spectrum: 0.3054061448201537
color:
  lightness: 0.7497372429352254
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  saturation: 0.6114414827898145
  brandStrength: 0.2309358853381127
  rhythmicContrast: 0.3781698099337518
content_rating:
  adult: false
typography_spectrum: 0.5259122208226472
opengraph: {}
title: keralum media
url: 'http://keralum.com/'
