name: keralum
analytics:
  google: ca-pub-2012905995297484
github: true
description: fast and simple media
author:
  name: Shaine Mata
  url: 'http://www.keralum.com'
  email: shaine@keralum.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f8b38975-9f6b-4937-a191-ad2353702091.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f8b38975-9f6b-4937-a191-ad2353702091.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      app_links: []
      related: []
      description: ''
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: 8a0cf19c-6e3a-4055-b9f4-a76e58956d27
    name: About
    type: content
  - id: 52537b89-815f-4e3f-8103-738db69d8eaf
    name: Home
    type: content
  - id: 282b4288-344f-4345-a791-4b015808843f
    name: Contact
    type: content
  - id: 427e5ba1-2c22-4f2b-8b6b-c8e5a5e9a36b
    name: Works
    type: content
layout_spectrum: 0.3054061448201537
color:
  lightness: 0.7497372429352254
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  saturation: 0.6114414827898145
  brandStrength: 0.2309358853381127
  rhythmicContrast: 0.3781698099337518
content_rating:
  adult: false
typography_spectrum: 0.5259122208226472
opengraph: {}
title: keralum media
url: 'http://keralum.com/'
